name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SERVER: production

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint (if available)
        run: |
          if npm run | grep -q "lint"; then npm run lint; else echo "No lint script"; fi
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
